[Global]
Actiu=1
Timer=10
Organitzacio=Granja Roca
ProgramaInstallacio=E:\GRoca\Setup\AndorBot\Disk01\installe.exe
FitxerLog=c:\Archivos de programa\AndorSoft\AndorBot\AndorBot.log

[Tasques]
;Paràmetres:
; 1:	Tipus tasca (1:Custom, 2:Windows, 3:DOS)
; 2:	Iconitzar (0:No, 1:Si)
; 3:	MonoTasca (0:No, 1:Si)
; 4:	Programa
; 5:	[Param1;[Param2;...]]
; 6:	Descripció
; 7:	Logar tasca (0:No, 1:Si)
; 8:	Estat (0:inactiu, 1:actiu)
; 9:	Hora inici
; 10:	Hora límit
; 11:	Període: minuts entre cada activació (0 si només 1 activació al dia)
; 12:	Espera: minuts entre cada reintent (0 si no hi ha reintents)
; 13:   Vida de la tasca en minuts (actiu només si 1:=1 i 3: = 0)
; 14:	Data pròxima activació
; 15:	Hora pròxima activació
; 16:	Data última activació
; 17:	Hora última activació
; 18:	Resultat última activació (0:Error, 1:OK)

Tasca1=1;1;1;c:\archiv~1\andorsoft\groca\grobatch.exe;NetejarLog C:\Archivos de programa\AndorSoft\AndorBot\AndorBot.log,15;Neteja AndorBot.log;1;1;0000;0000;0;0;0;20000720;0000;20000719;0000;1
Tasca2=1;1;1;c:\archiv~1\andorsoft\groca\grobatch.exe;NetejarLog C:\Archivos de programa\AndorSoft\GRoca\GRoca.log,15;Neteja GRoca.log;1;1;0000;0000;0;0;0;20000720;0000;20000719;0000;1
Tasca3=1;1;0;c:\archiv~1\andorsoft\groca\grobatch.exe;Reindexar;Reindexació;1;1;0001;0001;0;0;15;20000720;0001;20000719;0006;1
Tasca4=1;1;1;c:\archiv~1\andorsoft\groca\grobatch.exe;GenerarCliTPV E:\Groca\Syncro\Botiga01\,0,01;Generar fitxers TPV 01;1;1;0100;0159;0;60;10;20000720;0100;20000719;0100;1
Tasca5=1;1;1;c:\archiv~1\andorsoft\groca\grobatch.exe;GenerarCliTPV E:\Groca\Syncro\Botiga03\,0,03;Generar fitxers TPV 03;1;1;0100;0159;0;60;10;20000720;0100;20000719;0102;1
Tasca6=1;1;1;c:\archiv~1\andorsoft\groca\grobatch.exe;GenerarCliTPV E:\Groca\Syncro\Botiga04\,0,04;Generar fitxers TPV 04;1;1;0100;0159;0;60;10;20000720;0100;20000719;0105;1
Tasca7=1;1;1;c:\archiv~1\andorsoft\groca\grobatch.exe;GenerarCliTPV E:\Groca\Syncro\Botiga10\,1,10;Generar fitxers TPV 10;1;1;0100;0159;0;60;10;20000720;0100;20000719;0107;1
Tasca8=1;1;1;c:\archiv~1\andorsoft\groca\grobatch.exe;GenerarCliTPV E:\Groca\Syncro\Botiga15\,1,15;Generar fitxers TPV 15;1;1;0100;0159;0;60;10;20000720;0100;20000719;0110;1
Tasca9=1;1;1;c:\archiv~1\andorsoft\groca\grobatch.exe;GenerarCliTPV E:\Groca\Syncro\Botiga18\,1,18;Generar fitxers TPV 18;1;1;0100;0159;0;60;10;20000720;0100;20000719;0113;1
Tasca10=1;1;1;c:\archiv~1\andorsoft\groca\grobatch.exe;GenerarCliTPV E:\Groca\Syncro\Botiga20\,2,20;Generar fitxers TPV 20;1;1;0100;0159;0;60;10;20000720;0100;20000719;0115;1
Tasca11=1;1;1;c:\archiv~1\andorsoft\groca\grobatch.exe;GenerarCliTPV E:\Groca\Syncro\Botiga21\,2,21;Generar fitxers TPV 21;1;1;0100;0159;0;60;10;20000720;0100;20000719;0118;1
Tasca12=3;0;0;C:\Andorsoft\Scripts\EnviarTpv.cmd;01;Traspàs fitxersTPV 01;1;1;0200;0209;0;10;10;20000720;0200;20000719;0200;1
Tasca13=3;0;0;C:\Andorsoft\Scripts\EnviarTpv.cmd;03;Traspàs fitxersTPV 03;1;1;0210;0219;0;10;10;20000720;0210;20000719;0210;1
Tasca14=3;0;0;C:\Andorsoft\Scripts\EnviarTpv.cmd;04;Traspàs fitxersTPV 04;1;1;0220;0229;0;10;10;20000720;0220;20000719;0220;1
Tasca15=3;0;0;C:\Andorsoft\Scripts\EnviarTpv.cmd;10;Traspàs fitxersTPV 10;1;1;0230;0239;0;10;10;20000720;0230;20000719;0230;1
Tasca16=3;0;0;C:\Andorsoft\Scripts\EnviarTpv.cmd;15;Traspàs fitxersTPV 15;1;1;0240;0249;0;10;10;20000720;0240;20000719;0240;1
Tasca17=3;0;0;C:\Andorsoft\Scripts\EnviarTpv.cmd;18;Traspàs fitxersTPV 18;1;1;0250;0259;0;10;10;20000720;0250;20000719;0250;1
Tasca18=3;0;0;C:\Andorsoft\Scripts\EnviarTpv.cmd;20;Traspàs fitxersTPV 20;1;1;0300;0309;0;10;10;20000720;0300;20000719;0300;1
Tasca19=3;0;0;C:\Andorsoft\Scripts\EnviarTpv.cmd;21;Traspàs fitxersTPV 21;1;1;0310;0319;0;10;10;20000720;0310;20000719;0310;1
Tasca20=1;1;1;c:\archiv~1\andorsoft\groca\grobatch.exe;IntegrarCliServ;Integració de les vendes;1;1;0400;0400;0;60;10;20000720;0400;20000719;0400;1
Tasca21=

[Resultats]
;  -1: Error desconegut, mirar el log
;   0: OK
;   1: No s'ha pogut executar el programa
;   2: Tasca desconeguda
;   3: Falta paràmetre
;   4: No es pot crear fitxer
;   5: No es pot obrir fitxer
;   6: No es pot suprimir fitxer
;   7: No es pot crear carpeta
;   8: Registre no trobat
;   9: No es pot copiar fitxer
;  10: No es pot escriure dins el fitxer
;  11: Fitxer temporal no creat
;  12: No es pot comprimir el fitxer
;  13: No es pot descomprimir el fitxer
;  14: No es pot moure el fitxer
;  15: No es pot bloquejar la base de dades
;  16: No es pot copiar un registre
;  17: Error de duplicats o d'integritat
;  18: Fitxer no trobat
;  19: Carpeta no trobada
; 100: No disponible
; 101: Fitxer dat corromput
; 102: Problemes al establir la connexió
; 103: Problemes de desconnexió
; 104: Queden clients per tractar
; 105: No s'ha pogut preparar els canvis
; 106: No s'ha pogut sincronitzar els canvis
; 107: No s'ha trobat una clau primària
; 108: No s'ha pogut canviar l'estat del servidor

Tasca1=
CaducitatTasca1=
CaducitatTasca2=
Tasca2=
CaducitatTasca3=
Tasca3=
CaducitatTasca4=
Tasca4=
Tasca5=
Tasca6=
Tasca7=
Tasca8=
Tasca9=
Tasca10=
Tasca11=
CaducitatTasca20=
Tasca20=

[Coordenades]
TascaLeft=161
TascaTop=71
AndorbotLeft=233
AndorbotTop=23
SotmetretascaLeft=313
SotmetretascaTop=233
